server:
  port: 8002
  
spring:
  application:    name: ACCOUNT-SERVICE  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adarsha
    username: root
    password: 8411@mysql
  jpa:    hibernate:      ddl-auto: update
      
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost